import type { Metadata } from "next";
import Image from "next/image";
import PageShell from "@/components/layout/PageShell";
import { container, title, copy, sectionHead } from "@/components/ui/styles";

export const metadata: Metadata = { title: "About — Atlas Engine", description: "The story behind Atlas Engine, an open-source game engine developed by Neutral Software and created by Max Van den Eynde." };

export default function About() {
    return <PageShell>
        <header className={`${container} pb-16`}><h1 className="page-title">Serious tools.<br />Room to imagine.</h1><p className="page-lede mt-8 max-w-2xl">We build software that helps developers shape worlds. Atlas is where that idea begins.</p></header>
        <figure className={`${container} relative aspect-[2.2] overflow-hidden rounded-2xl max-[760px]:aspect-[1.2]`}><Image src="/images/landingDay.png" alt="A glass dragon overlooking an expansive mountain landscape rendered in Atlas" fill priority sizes="(max-width: 760px) 100vw, 1200px" className="object-cover"/></figure>
        <section className={`${container} py-28 max-[760px]:py-16`}>
            <div className={sectionHead}><h2 className={title}>A game engine<br />with a point of view.</h2><div className={`${copy} space-y-5`}><p>Atlas Engine began in 2025 with a direct goal: give developers a modern engine that feels understandable from the first project to the deepest rendering system.</p><p>Today, Atlas is developed by Neutral Software. It is our first major product and the place where our ideas about tools, openness and creative control become real.</p></div></div>
            <div className="grid grid-cols-2 gap-16 border-t border-[#d9ded4] pt-12 max-[760px]:grid-cols-1 max-[760px]:gap-10"><div><h3 className="mb-5 text-2xl tracking-tight">Tools that get out of your way.</h3><p className={copy}>The editor should help you move quickly, the runtime should remain focused, and the source should always be available when your project needs to go beyond the standard workflow. Spend less time negotiating with your tools and more time shaping what you have in mind.</p></div><div><h3 className="mb-5 text-2xl tracking-tight">Built in public.</h3><p className={copy}>Atlas is open source. Its renderer, runtime, editor and supporting modules are developed in the public Neutral Software repository. Systems should have clear boundaries, decisions should be inspectable, and contributors should be able to improve the engine.</p><a href="https://github.com/neutralsoftware/atlas" className="mt-5 inline-block text-sm font-medium text-[#2e8b7f] underline underline-offset-4">Join us on GitHub</a></div></div>
        </section>
        <section className="bg-[#e9ede6] py-24 max-[760px]:py-16"><div className={`${container} grid grid-cols-[1fr_1.5fr] gap-20 max-[760px]:grid-cols-1 max-[760px]:gap-8`}><h2 className={title}>A note from<br />the creator.</h2><div className="space-y-6 text-lg leading-relaxed text-[#52604f]"><p>I started Atlas after several earlier attempts at building a game engine. Each one taught me more about systems programming, graphics and the difference between technology that is impressive and a tool that is genuinely useful.</p><p>Atlas is where those lessons came together. I want it to be technically serious without becoming distant, and flexible without becoming incoherent. Neutral Software gives that work a lasting home and a wider purpose: build software that helps developers shape worlds.</p><p>Keep on creating,</p><Image src="/images/sign.png" alt="Max Van den Eynde’s signature" width={200} height={100} className="h-auto w-40"/><p className="text-sm"><strong className="block text-[#242923]">Max Van den Eynde</strong>Founder and Director, Neutral Software</p></div></div></section>
    </PageShell>;
}
